Add dynamic/deploy time properties appropriately from resource_configuration block
vmware-archive/legacy-terraform-provider-vra7 pull request #25
Opened 2017-12-05 08:04 UTC by cars

This is re: #21 (The disk add issue @Marcvd316 pointed out earlier) This PR allows setting properties on resources at deploy time even if they weren't already on the blueprint/component.  So for a given blueprint with two VMs (each of which has a base 60GB disk) 
![image](https://user-images.githubusercontent.com/137110/33595295-51f56080-d94c-11e7-8a63-9efa17dfc899.png)

One can do something like
```
resource "vra7_resource" "TF_CustomProp_Test"  {
    count = 1
    catalog_name = "TF_VRA_2VM_BP"
    resource_configuration = {
        //******* VM 1 ****************
        //props available on all vms
        vm1.cpu = 1
        vm1.memory = 2048
        //custom properties that come from the blueprint
        vm1.lab.vm.prop1 = "vm1 Prop1a"
        //properties being added at deploytime
        //random property
        vm1.TestProp1 =  "vm1DynamicProp1"
        //Add a second disk (Disk1) to VM1 and make it 11GB
        vm1.VirtualMachine.Disk1.Size = 11
        //******* VM 2 ****************
        //props available on all VMs
        vm2.cpu = 2
        vm2.memory = 4096
        //properties from the blueprint
        vm2.lab.vm2.prop1 = "vm2 prop1a"
        //properties being added at deploytime
        vm2.DynamicProp1 =  "vm2DynamicProp1"
        vm2.DynamicProp2 =  "vm2DynamicProp2"
        vm2.VirtualMachine.Disk1.Size = 31
  }
```
And the result will be two VMs:
- VM1 with the base disk (Disk0) as defined in the blueprint plus a new second 11GB  disk specified at deploytime. 
- VM2 with the base disk (Disk0) as defined in the blueprint plus a new second disk of 31GB specified at deploytime. 

This leaves the functionality in the **catalog_configuration** block alone so that its possible to still do things like specify  a disk to be added to **_all_** VMs or setting _deploymentName

```
  catalog_configuration = {
    //Overwrite default values on properties 
    lab.bp.prop1 = "TF Blueprint Prop 1",
    lab.bp.Prop2 = "TF Blueprint Prop 2"
    // Change name of deployment from UBU_LTS_Ansible_tf3 copy-NNNNNNNNN
    //  to something more friendly
    _deploymentName = "Custom Properties Test"
    // Here's a deployment time property to add a 3rd disk to 
    //   _every_ VM in this catalog request
    VirtualMachine.Disk2.Size = 20
  }
  
```

2017-12-07 18:39 UTC, Marcvd316 approved these changes
Looks good! Awesome functionality!

2018-01-24 17:15 UTC, markpeek requested changes
Looks good except for the comment around log.Printf() calls.

2018-01-24 17:15 UTC, markpeek commented on vrealize/resource.go
> +	log.Printf("In Add TemplateValue field = [%s], value = [%+v],tInt = [%+v]", field, value, templateInterface)
There are several log.Printf() calls (like this one) in this PR that appear to be more debugging vs. general informational. Could these get removed or commented out?

2018-01-26 04:18 UTC, cars commented
@markpeek I think I cleared up the extraneous logging.. let me know if there's anything else.

2018-01-29 17:33 UTC, markpeek approved these changes

2018-01-29 17:33 UTC, merged

2018-01-29 17:34 UTC, markpeek commented
Thank you for the PR @cars