Update resource_configuration schema
vmware-archive/legacy-terraform-provider-vra7 pull request #27
Opened 2017-12-13 10:29 UTC by virajindasrao

**Update resource_configuration schema - Update resource details (component level update feature)**
New feature added in order to consider new updates in resource_configuration resource schema.

Signed-off-by: Viraj Indasrao <virajindasrao@gmail.com>

2018-01-24 23:44 UTC, markpeek commented
Is there a test (manual or automated) that can be added to verify this is working as advertised?

2018-04-02 13:54 UTC, Marcvd316 commented
Hi @virajindasrao,
Would this allow any type of resource action (vRA builtin actions and custom actions?) to be executed on any type of item? (Deployment, VM, XaaS object, etc.)

2018-04-03 05:50 UTC, virajindasrao commented
Hi @Marcvd316 
This will allow a user to update the configuration of any deployment present in a provisioned item.
For remaining item actions, I am working on it.

2018-04-17 12:57 UTC, afurlani24 commented
When will this be reviewed so that we can use it?  Thanks

2018-04-30 07:33 UTC, raghavav commented on vrealize/resource.go
> +	if d.HasChange("resource_configuration") {
For better readability of the method, use the following:

if !d.HasChange("resource_configuration") {
  return nil
}

2018-04-30 19:59 UTC, raghavav commented on vrealize/resource.go
>  //Function use - to update centOS 6.3 machine present in state file
// Function use - to update a vRA 7 Deployment

2018-05-01 04:35 UTC, raghavav commented on vrealize/resource.go
> +		templateResources, errTemplate := client.GetResourceViews(requestMachineID)
'templateResources' is not a very good name for this variable.
Call it 'resources' or 'deploymentResources'

2018-05-01 04:36 UTC, raghavav commented on vrealize/resource.go
> +		//Iterate over the template content elements
// Iterate over the resources in the deployment

2018-05-01 04:38 UTC, raghavav commented on vrealize/resource.go
> +		reconfigGetLinkTitle := "GET Template: {com.vmware.csp.component.iaas.proxy.provider@resource.action.name." +
const reconfigGetLinkRel = "GET ...."
Likewise
const reconfigPostLinkRel = "POST: ..."

2018-05-01 04:43 UTC, raghavav commented on vrealize/resource.go
> +		for item := range templateResources.Content {
Why not just
for item, value := range templateResources.Content
  mapData := value.(map[string]interface{})

Also 'mapData' sounds too generic. I would prefer 'resourceMap' or 'resourceDetails'

2018-05-01 04:43 UTC, raghavav commented on vrealize/resource.go
> +			childData := mapData["data"].(map[string]interface{})
Use 'resourceSpecificData' instead of 'childData'

Use 'resourceSpecificLinks' instead of 'childLinks'

2018-05-01 05:16 UTC, raghavav commented on vrealize/resource.go
> +			//If component is not empty
We need a different check here:

if mapData["resourceType"] != "Infrastructure.Virtual" {
  continue;
}

Then, also change to
if childData["Component"] == nil {
  continue;
}

2018-05-01 05:29 UTC, raghavav commented on vrealize/resource.go
> +			if childData["Component"] != nil {
You can avoid this indentation if you do the previous check for childData["Component"] == nil

2018-05-01 05:34 UTC, raghavav commented on vrealize/resource.go
> +						reconfigGetLink = linkInterface["href"].(string)
Add 'continue;'

2018-05-01 05:34 UTC, raghavav commented on vrealize/resource.go
> +						reconfigPostLink = linkInterface["href"].(string)
Add continue;

2018-05-01 05:50 UTC, raghavav commented on vrealize/resource.go
> +					}
Ideally, you should break out of the loop as soon as the two variables (reconfigGetLInk and reconfigPostLink) are non-nil

2018-05-01 06:00 UTC, raghavav commented on vrealize/resource.go
> +					if strings.Contains(configKey, componentName+".") {
strings.HasPrefix is a more correct method to use.

2018-05-01 07:30 UTC, raghavav commented on vrealize/resource.go
> +		if childData["Component"] != nil {
See comments in the updateResource function and use the same here.

2018-05-01 17:05 UTC, raghavav commented on vrealize/resource.go
>  type ResourceViewsTemplate struct {
The ResourceView is not quite a 'Template'.
It is really just ResourceView.

'Templates' are used as skeletons to fill data in before submitting. That's not the case with ResourceView.

2018-05-01 17:39 UTC, raghavav commented on vrealize/resource.go
Fix Function use text.

This has nothing to do with a specific Centos 6.3 machine.
This is about reading configuration of vra 7 deployments.

2018-05-01 17:46 UTC, raghavav commented on vrealize/resource.go
> +	templateResources, errTemplate := client.GetResourceViews(requestMachineID)
'requestMachineID' is an incorrect name.

What you have here is a catalog request id. This is the id of the catalog request that originally created the Deployment resource.

Please fix the variable name in all places.

2018-05-01 17:53 UTC, raghavav commented on vrealize/resource.go
> +			resourceAction := new(ResourceActionTemplate)
Please insert a comment on why you have to retrieve the 'reconfigure' template in order to get resource information. One would expect that you can directly get this information from the resourceView.

2018-05-01 17:57 UTC, raghavav commented on vrealize/resource.go
> +	for index1 := range resourceConfiguration {
This loop should go into a separate utility function.
Clearly document what that function is for.

2018-05-01 17:57 UTC, raghavav commented on vrealize/resource.go
> +					changed = true
If all you are doing is to figure out if the resource has changed, you don't need to loop through all values.
You can break out at this point.

2018-05-08 05:11 UTC, virajindasrao commented on vrealize/resource.go
> +	if d.HasChange("resource_configuration") {
Cannot return from this point. Because there are few more schema updates to be added in future.

2018-05-08 05:11 UTC, virajindasrao commented on vrealize/resource.go
Completed.

2018-05-08 05:14 UTC, virajindasrao commented on vrealize/resource.go
> +			resourceAction := new(ResourceActionTemplate)
Few properties cannot be determined without a Recufonfigure template. This the only template which has same name and values like we mention in tf config file.

2018-05-18 22:57 UTC, raghavav commented
Please run 'make check' to see the gofmt failures. Let's make sure the reviews are always kept clean.

2018-05-22 03:58 UTC, raghavav commented on vrealize/resource.go
> +func (c *APIClient) GetResourceViews(ResourceID string) (*ResourceView, error) {
Rename function to GetDeploymentState. That would be a more appropriate name for this function.

2018-05-22 03:59 UTC, raghavav commented on vrealize/resource.go
>  //GetResourceViews - To read resource configuration
Change comment to:
// GetDeploymentState - Read the state of a vRA7 Deployment

2018-05-22 04:09 UTC, raghavav reviewed
I am requesting changes here that improve code readability by using more appropriate names for functions and by fixing up comments. Do take care of this as we drive towards merging this pull request.

2018-05-22 06:46 UTC, raghavav commented on vrealize/resource.go
> +	//Get requester machine ID from schema.dataresource
Change comment to:
//Get the ID of the catalog request that was used to provision this Deployment.

2018-05-22 06:46 UTC, raghavav commented on vrealize/resource.go
> +			//If component is not empty
This comment needs to be two lines down.

2018-05-22 06:46 UTC, raghavav commented on vrealize/resource.go
> +			if resourceMap["Component"] != "Infrastructure.Virtual" {
Are you sure there is a field called 'Component' in a resource entry in the resourceViews map?
I don't see it in my example.
Can you paste an example of the resourceViews map you are looking at?

Or did you mean resourceMap["resourceType"]?
If so, what you need here is
if resourceMap["resourceType"] != "Infrastructure.Virtual" {
    continue;
}

2018-05-22 06:46 UTC, raghavav commented on vrealize/resource.go
> +					if linkInterface["rel"] == reconfigPostLinkTitleRel {
else if

2018-05-22 06:46 UTC, raghavav commented on vrealize/resource.go
> +				response2, _ := client.HTTPClient.New().Post(reconfigPostLink).
Looks like there is no check to see if there is any change to the fields of this specific machine before posting the reconfigure action. We do not want to be firing reconfigure calls unless there is a need.

2018-05-22 06:46 UTC, raghavav commented on vrealize/resource.go
>  	//Get requester machine ID from schema.dataresource
Change comment to:
//Get the ID of the catalog request that was used to provision this Deployment.

2018-05-29 11:28 UTC, virajindasrao commented on vrealize/resource.go
> +func (c *APIClient) GetResourceViews(ResourceID string) (*ResourceView, error) {
Function sIgnature changed.

2018-05-29 11:29 UTC, virajindasrao commented on vrealize/resource.go
>  //GetResourceViews - To read resource configuration
Done

2018-05-29 11:29 UTC, virajindasrao commented on vrealize/resource.go
> +	//Get requester machine ID from schema.dataresource
Comment changed.

2018-05-29 11:33 UTC, virajindasrao commented on vrealize/resource.go
> +			if resourceMap["Component"] != "Infrastructure.Virtual" {
Thanks for the pointing out this error and apologies. I missed that comment change in the last review. Fixed now.

2018-05-29 11:42 UTC, virajindasrao commented on vrealize/resource.go
> +				response2, _ := client.HTTPClient.New().Post(reconfigPostLink).
check added to verify if machine configuration is changed

2018-05-29 11:43 UTC, virajindasrao commented on vrealize/resource.go
>  	//Get requester machine ID from schema.dataresource
Done

2018-06-02 23:25 UTC, raghavav commented on vrealize/resource.go
> +	if d.HasChange("resource_configuration") {
ok

2018-06-02 23:30 UTC, raghavav commented on vrealize/resource.go
> +			Computed: true,
I have a very fundamental question here. If you turn resource_configuration into a computed field, how does the 'plan' operation work?
For example, if a change is made only to a resource-configuration field, Terraform will not use that change to generate a plan. Or am I missing something?

2018-06-04 04:52 UTC, virajindasrao commented on vrealize/resource.go
> +			Computed: true,
Computed type field means that field can be updated from plugin end also during execution.
If a computed field is false then it will consider a change as a user change and will consider for 'plan'.

2018-06-04 22:04 UTC, raghavav requested changes

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +func updateResourceConfigurationMap(resourceConfiguration map[string]interface{}, childConfig map[string]interface{}, changed bool) (map[string]interface{}, bool) {
Why is 'changed' passed in as in input here? It should only be the return value of the function.

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +	for index1 := range resourceConfiguration {
Not 'index1' or 'index2'. These are keys. 'index' implies a number.
And do just pull out the key and value in one shot.

for configKey, configValue := range resourceConfiguration

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +func updateResourceConfigurationMap(resourceConfiguration map[string]interface{}, childConfig map[string]interface{}, changed bool) (map[string]interface{}, bool) {
better comments please.
What are the inputs to this function? It seems to take a resource-config map. What is that other 'child-config' map?
What kind of update of the resource_configuration map (not schema map) does this function perform?

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +				splitedArray := strings.Split(index1, index2+".")
Use TrimPrefix not Split

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +			if strings.Contains(index1, index2+".") {
Use 'HasPrefix' not 'Contains'.

Is there a reason you are not using HasPrefix consistently even within this code review?

2018-06-04 22:04 UTC, raghavav commented on vrealize/actions.go
> +func getactionURL(template *ResourceView, relationVal string) (templateactionURL string) {
I feel like there is the following problem with the implementation here:

You are looping through all the resources in a deployment and you are returning the matching action on the 'last' single-resource (machine) within that deployment. There may be multiple machines with the same matching 'rel' link value, so how do you know you are returning the right one for the right machine.
The way this function looks to me, you will end up powering on or off the wrong machine in a Deployment. Am I missing something or misreading something?

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +			resourceAction := new(ResourceActionTemplate)
Could you insert this comment in the code please.

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +	var usedConfigKeys []string
Please see review comments in PR #55. I suggest we can do without tracking usedConfigKeys like this.

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +				//Iterate over the links present in content elements
The code would be more readable if the link finding code was put into a separate private function.

In general, this method needs to be broken up into smaller functions that do some of the key pieces of independent work like this one.

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +				if configChanged != false {
If the last item that you checked in resource_configuration did not change, you will see configChanged to be false. However there may have been other config fields that have changed. This looks like a bug to me.

You are setting a shared variable in every iteration of the loop. You should not set it back to false if it is already true.

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +					if strings.HasPrefix(configKey, componentName+".") {
This pattern of trimming out the prefixes of resource-configuration fields is reappearing in multiple places. It is used during creation, update, as well as when reading a resource.

[Future change: I strongly recommend abstracting out the core logic into a function that takes care of converting to and from maps with different kinds of keys. That way we can address bugs in one place. As you can see in my review, I already see issues with using string.Contains instead of string.HasPrefix as well as with not using string.TrimPrefix.]

In the meantime, please see PR #55 for more comments in this area. Please incorporate those same comments as applicable here too. Comments that apply include:
- use strings.TrimPrefix
- rename splitedArray
- changes in the comments in the code

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +				for configKey := range resourceConfiguration {
for configKey, configValue := range resourceConfiguration

and use 'configValue' directly in the loop.

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +					resourceAction2 := new(ResourceActionTemplate)
The invoking of the reconfigure operation can be a separate private function instead of so many lines of inlined code. Functions make the code much more readable.

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +				resourceAction := new(ResourceActionTemplate)
Use a separate private function to invoke the GET call to retrieve the resource reconfiguration template.

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +//getTemplateFieldValue is use to check and return value of argument key
It is interesting that you are doing this recursively to any number of levels of the map. Is there a strong use-case for this? Do you have an example?
If not, it may be best to not do this. A field such as ' name' may mean different things depending on where it appears. So just blindly matching it any any level of a hierarchy of maps may be incorrect. Could you please explain the rationale?

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +					if reflect.ValueOf(updatedValue).Kind() == reflect.Float64 {
Move all this type conversion logic directly into getTemplateFieldValue. Let us just standardize that that function returns a string. Returning an interface{} is a bit weird for such a specific method.

2018-06-04 22:04 UTC, raghavav commented on vrealize/resource.go
> +	for i := range template {
'i' normally indicates an integer. This one is a map key. Please use a better variable.
I recommend using
for key, value := range template

2018-06-04 22:28 UTC, raghavav commented on vrealize/resource.go
> +			Computed: true,
From a separate email thread it looks like this may not be a concern:

From @virajindasrao:
"If the values are updated from user side then create and apply will be considered by tf.
But if updated by plugin then it will not be considered for the update and there is no need for that.
Because plugin only updates the values which are present on-prem."

Viraj, please feel free to provide more information so we can record it here for posterity.

2018-06-06 06:56 UTC, virajindasrao commented on vrealize/resource.go
> +			if strings.Contains(index1, index2+".") {
I will make sure to avoid such things in future.

2018-06-07 10:33 UTC, virajindasrao commented on vrealize/actions.go
> +func getactionURL(template *ResourceView, relationVal string) (templateactionURL string) {
There is a slight difference between machine and deployment action template link titles.
deployment has 'deployment' keyword in it whereas machine has 'virtual' keyword.

example:
deploynet - GET Template: {com.vmware.csp.component.cafe.composition@resource.action.deployment.destroy.name}

machine - GET Template: {com.vmware.csp.component.iaas.proxy.provider@resource.action.name.virtual.Destroy}

2018-06-07 11:43 UTC, virajindasrao commented on vrealize/resource.go
> +	var usedConfigKeys []string
REmoved in another PR

2018-06-07 12:15 UTC, virajindasrao commented on vrealize/resource.go
> +					if strings.HasPrefix(configKey, componentName+".") {
Sure @raghavav . I will take cafe in future about these things.

2018-06-07 16:31 UTC, raghavav commented on vrealize/actions.go
> +func getactionURL(template *ResourceView, relationVal string) (templateactionURL string) {
I am not talking about the 'Deployment' resource here. I am asking about the scenario where there are multiple machines in the given deployment. There may be any number of machines that all look similar and they will all have the same actions on them.

2018-06-18 19:11 UTC, raghavav commented on vrealize/resource.go
> +func updateResourceConfigurationMap(resourceConfiguration map[string]interface{}, childConfig map[string]interface{}, changed bool) (map[string]interface{}, bool) {
This review item is not addressed in the changes.

2018-06-18 19:12 UTC, raghavav commented on vrealize/resource.go
> +	for index1 := range resourceConfiguration {
This review item is not addressed in the changes.

2018-06-18 19:12 UTC, raghavav commented on vrealize/resource.go
> +				splitedArray := strings.Split(index1, index2+".")
The code still has 'Split' in it. This review comment is not addressed.

2018-06-18 19:13 UTC, raghavav commented on vrealize/resource.go
> +			if strings.Contains(index1, index2+".") {
This review item is not addressed in the changes. The code still uses 'Contains'.

2018-06-18 21:57 UTC, raghavav commented on vrealize/resource.go
> +	if d.HasChange("resource_configuration") {
Done

2018-06-18 21:58 UTC, raghavav commented on vrealize/resource.go
>  //Function use - to update centOS 6.3 machine present in state file
Done

2018-06-18 22:20 UTC, raghavav commented on vrealize/resource.go
> +func (c *APIClient) GetResourceViews(ResourceID string) (*ResourceView, error) {
Done

2018-06-18 22:21 UTC, raghavav commented on vrealize/resource.go
> +func (c *APIClient) GetResourceViews(ResourceID string) (*ResourceView, error) {
Done

2018-06-18 22:36 UTC, raghavav commented on vrealize/resource.go
> +			if resourceMap["Component"] != "Infrastructure.Virtual" {
Done

2018-06-18 23:30 UTC, raghavav commented on vrealize/resource.go
> +			Computed: true,
Done

2018-06-18 23:30 UTC, raghavav commented on vrealize/resource.go
> +func updateResourceConfigurationMap(resourceConfiguration map[string]interface{}, childConfig map[string]interface{}, changed bool) (map[string]interface{}, bool) {
Done.

2018-06-18 23:30 UTC, raghavav commented on vrealize/resource.go
> +	for index1 := range resourceConfiguration {
Done

2018-06-18 23:31 UTC, raghavav commented on vrealize/resource.go
> +				splitedArray := strings.Split(index1, index2+".")
This review comment has not been addressed yet.

2018-06-18 23:31 UTC, raghavav commented on vrealize/actions.go
> +func getactionURL(template *ResourceView, relationVal string) (templateactionURL string) {
Done.

2018-06-18 23:33 UTC, raghavav commented on vrealize/resource.go
> +				if configChanged != false {
Done

2018-06-18 23:33 UTC, raghavav commented on vrealize/resource.go
> +//getTemplateFieldValue is use to check and return value of argument key
This comment has not been addressed.

2018-06-18 23:34 UTC, raghavav commented on vrealize/resource.go
> +					if reflect.ValueOf(updatedValue).Kind() == reflect.Float64 {
This comment has not been addressed yet.

2018-06-18 23:35 UTC, raghavav commented on vrealize/resource.go
> +	for i := range template {
Done

2018-06-19 00:00 UTC, raghavav requested changes
The changes look very good at this point. Most review comments have been addressed.
However, a couple of them have not. And I have also added a couple of small comments on the new changes. I think this pull request is close to ready. Let us get this in ASAP.
Thanks
Vijay

2018-06-19 00:00 UTC, raghavav commented on vrealize/resource.go
> +func readVMReconfigActionUrls(GetDeploymentStateData *ResourceView) (map[string]interface{}) {
Nice! Good to see this function that captures the links by component!

2018-06-19 00:00 UTC, raghavav commented on vrealize/resource.go
> +		const reconfigGetLinkTitleRel = "GET Template: {com.vmware.csp.component.iaas.proxy.provider@resource.action.name." +
These constants are no longer needed here. They are defined and used in the readVMReconfigActionUrls function.

2018-06-19 00:00 UTC, raghavav commented on vrealize/resource.go
> +//func changeTemplateValue(templateInterface map[string]interface{}, field string, value interface{}) (map[string]interface{}, bool) {
There is no need to leave commented-out code here. Code is always accessible through source control history.
I would remove this.

2018-06-19 00:00 UTC, raghavav commented on vrealize/resource.go
> +						configValue1 =
In an earlier review I asked to move all this casting logic directly into the getTemplateFieldValue function. That would make this code nice and concise. We can assume that the getTemplateFieldValue function returns a string.

2018-06-19 00:00 UTC, raghavav commented on vrealize/resource.go
> +			templateInterface[key], replaced = changeTemplateValue(template, field, value)
This recursive call is still bothering me a little, as I said in an earlier review. Could you please respond to that comment? Thx

2018-06-19 00:05 UTC, raghavav requested changes

2018-06-19 00:05 UTC, raghavav commented on vrealize/resource.go
> +				splitedArray := strings.SplitN(configKey, dataValue+".", 2)
This is one more unaddressed review comment. It would be more appropriate to use strings.TripPrefix instead of Split or SplitN.

2018-06-19 05:52 UTC, virajindasrao commented on vrealize/resource.go
> +		const reconfigGetLinkTitleRel = "GET Template: {com.vmware.csp.component.iaas.proxy.provider@resource.action.name." +
Removed.

2018-06-19 05:52 UTC, virajindasrao commented on vrealize/resource.go
> +//func changeTemplateValue(templateInterface map[string]interface{}, field string, value interface{}) (map[string]interface{}, bool) {
Removed.

2018-06-19 05:53 UTC, virajindasrao commented on vrealize/resource.go
> +						configValue1 =
Added separate function to convert interface to string

2018-06-19 05:54 UTC, virajindasrao commented on vrealize/resource.go
> +			templateInterface[key], replaced = changeTemplateValue(template, field, value)
As per my view, the key mentioned in resource_configuration keymap is allowed to add any k:v pair user wants. And that key can be at any level of a blueprint. That's why I have added the recursive call.

2018-06-19 05:54 UTC, virajindasrao commented on vrealize/resource.go
> +				splitedArray := strings.SplitN(configKey, dataValue+".", 2)
Done

2018-06-20 06:52 UTC, virajindasrao commented on vrealize/resource.go
> +			templateInterface[key], replaced = changeTemplateValue(template, field, value)
Let's make another PR to set a one level map update without a recursive call.

2018-06-20 18:23 UTC, raghavav commented on vrealize/resource.go
> +			templateInterface[key], replaced = changeTemplateValue(template, field, value)
Okay.

2018-06-20 18:51 UTC, raghavav commented on vrealize/resource.go
> +				splitedArray := strings.SplitN(configKey, dataValue+".", 2)
Yes, I see that you have updated this particular location which is in the CreateResource function.
However I still see a use of 'Split' in the UpdateResource function (line 482).
I will merge this PR in and we can address that one separately.

2018-06-20 19:04 UTC, raghavav approved these changes

2018-06-20 19:08 UTC, merged