Unit testing - code coverage
vmware-archive/legacy-terraform-provider-vra7 pull request #48
Opened 2018-04-24 12:24 UTC by virajindasrao

unit testing code coverage

Signed-off-by: Viraj Indasrao <virajindasrao@gmail.com>

2018-04-24 18:19 UTC, raghavav commented on vrealize/catalog.go
> +		return nil, fmt.Errorf("There %s total %d catalog(s) present with same name.\n%s\n"+
I see the use of the term 'catalog' throughout the code base.
vRA does not call the items you refer to by that term.
They are actually called 'catalog items'. Just calling them 'catalog' is confusing and misleading. This may be a good opportunity to fix the terminology.

2018-04-24 18:29 UTC, raghavav commented on vrealize/action_test.go
> +		httpmock.NewStringResponder(200, `{"links":[],"content":[{"@type":"CatalogResourceView","resourceId":"588f5e28-5572-495e-b104-e1237eaf2b98","iconId":"e5dd4fba-45ed-4943-b1fc-7f96239286be","name":"m
The line is too long to read. Can you break the input json into a more readable multi-line format?

2018-04-24 20:07 UTC, raghavav commented
Some documentation on how to run the tests would be good, even if it is as simple as (i) get the dependency (httpmock), and run 'go test -i'. This should go in the README.md file.

2018-04-24 21:30 UTC, raghavav commented on vrealize/action_test.go
> +	templateResources, errTemplate := client.GetResourceViews("666d77e3-7642-492d-aad1-82b8edd30e56")
Please use variables for these UUIDs. There are multiple of them in use and using variables will help readability. It is hard, otherwise, to be certain about the matching responder to a given call. You may also want to consider negative tests where there aren't matching resources, resulting in failure scenarios.

2018-04-24 21:37 UTC, raghavav commented on vrealize/catalog_test.go
> +func TestFetchCatalogByName(t *testing.T) {
Rename to 'TestFetchCatalogItemByName'

2018-04-24 21:37 UTC, raghavav commented on vrealize/catalog_test.go
> +func TestFetchCatalogByID(t *testing.T) {
Rename to 'TestFetchCatalogItemByID'

2018-04-24 23:16 UTC, raghavav commented on vrealize/catalog_test.go
> +func TestFetchCatalogByName(t *testing.T) {
Rename to 'TestFetchCatalogItemByName'

2018-04-24 23:17 UTC, raghavav commented on vrealize/catalog_test.go
> +	client = NewClient(
Do these credentials matter at all? If not, just say so in a comment.

2018-04-24 23:20 UTC, raghavav commented on vrealize/action_test.go
> +func TestPowerOFfAction(t *testing.T) {
Should be 'TestPowerOffAction'

2018-04-24 23:25 UTC, raghavav commented
General comment: It is generally best practice not to use actual tabs in code.
Code should be formatted to the desired indentation using spaces.
I wouldn't use this change to fix tabs. We could do that in a separate pull request.

2018-04-24 23:38 UTC, raghavav commented on vrealize/catalog.go
> +		punctuation := "are"
I think it is best to do the following, for better readability:

if len(catalogNameArray) == 1 {
    return nil, fmt.Errorf("Found a matching catalog item with the name \"%s\".", errorMessage)
else {
    return nil, fmt.Errorf("Found %d catalog items with the name. \n%s\n. Please select one from above.", len(catalogNameArray), errorMessage)
}

2018-04-24 23:38 UTC, raghavav commented on vrealize/catalog.go
> +		punctuation := "are"
Actually, I think you also have to account for the case of 'zero' matching catalog items. Does that fail cleanly?

2018-04-24 23:43 UTC, raghavav commented on vrealize/catalog.go
> +		punctuation := "are"
Finding '1' item with the name should not be an error case.
Why are you using '> 0' for the check here? Shouldn't it be >1?
And what happens when the number is '0'?

2018-04-24 23:49 UTC, raghavav commented on vrealize/catalog_test.go
> +	httpmock.RegisterResponder("GET", "http://localhost/catalog-service/api/consumer/entitledCatalogItemViews",
Need some more comments in this test.

For each test case, clearly document what you are setting up the mock to do and what the expected result is.
I do see some of that, but the intent is not clear on every test.

2018-04-25 11:39 UTC, virajindasrao commented on vrealize/catalog.go
> +		return nil, fmt.Errorf("There %s total %d catalog(s) present with same name.\n%s\n"+
Renamed all possible names.

2018-04-25 11:40 UTC, virajindasrao commented on vrealize/action_test.go
> +		httpmock.NewStringResponder(200, `{"links":[],"content":[{"@type":"CatalogResourceView","resourceId":"588f5e28-5572-495e-b104-e1237eaf2b98","iconId":"e5dd4fba-45ed-4943-b1fc-7f96239286be","name":"m
Added new line in all JSON strings to make it easier to read.

2018-04-25 11:41 UTC, virajindasrao commented on vrealize/catalog_test.go
> +func TestFetchCatalogByID(t *testing.T) {
Done

2018-04-25 11:41 UTC, virajindasrao commented on vrealize/catalog_test.go
> +	client = NewClient(
Not to worry about the values. All those are dummy values.

2018-04-25 11:41 UTC, virajindasrao commented on vrealize/action_test.go
> +func TestPowerOFfAction(t *testing.T) {
Renamed.

2018-04-25 11:42 UTC, virajindasrao commented on vrealize/catalog.go
> +		punctuation := "are"
Made changes accordingly.

2018-06-02 05:26 UTC, raghavav commented on vrealize/catalog_test.go
> +	client = NewClient(
I meant that I would like to see the comment in the actual code.

2018-06-02 05:49 UTC, raghavav commented on vrealize/catalog_test.go
> +	httpmock.RegisterResponder("GET", "http://localhost/catalog-service/api/consumer/entitledCatalogItemViews",
Could you please address this review comment.

2018-06-02 05:49 UTC, raghavav commented on vrealize/catalog_test.go
> +	client = NewClient(
I meant that I would like to see the comment in the actual code.

2018-06-02 05:49 UTC, raghavav commented on vrealize/catalog_test.go
> +	//Fetch catalog by correct and false name
What do you mean by 'correct' and 'false'?

Please put in more comments on what you are testing for in all these individual tests. It is worth documenting your intention.

2018-06-02 05:49 UTC, raghavav commented on vrealize/catalog_test.go
> +	//Fetch catalog item by correct and incomplete name
What is correct and yet incomplete?

2018-06-02 05:49 UTC, raghavav commented on vrealize/catalog_test.go
> +func TestFetchCatalogItemByID(t *testing.T) {
Please insert comments in the code that clearly state what each test case is doing.
Reading this intent will help other developers understand the nature of these tests and to make sure the code is kept in sync with that intent.

2018-06-02 05:49 UTC, raghavav commented on vrealize/resource.go
>  			return fmt.Errorf("No catalog found with name %v", d.Get("catalog_name").(string))
'catalog item' not 'catalog'.

Please make sure you consistently fix the use of 'catalog' vs 'catalog item' everywhere.

2018-06-02 05:49 UTC, raghavav commented on vrealize/resource_test.go
> +	strJson := `{"type":"com.vmware.vcac.catalog.domain.request.CatalogItemProvisioningRequest","catalogItemId":"e5dd4fba-45ed-4943-b1fc-7f96239286be","requestedFor":"jason@corp.local","businessGroupId"
Please make this more readable. Break it up into multiple lines.

2018-06-02 05:49 UTC, raghavav commented on vrealize/catalog.go
> +func (c *APIClient) readCatalogNameByID(catalogItemID string) (interface{}, error) {
Rename to 'readCatalogItemNameByID.
Update comment on function.

2018-06-02 05:49 UTC, raghavav commented on vrealize/catalog.go
> +	//Set REST call to get catalog item template
You mean 'Make a REST API call ...'

2018-06-02 05:49 UTC, raghavav commented on vrealize/catalog.go
>  func (c *APIClient) readCatalogIDByName(catalogName string) (interface{}, error) {
Any reason you did not fix the naming of this function and its parameters? Why only the variable on the next line?

2018-06-02 05:49 UTC, raghavav commented on vrealize/catalog.go
>  	//If multiple catalogs are present with provided catalog_name
catalog items

2018-06-02 05:49 UTC, raghavav commented on vrealize/resource.go
>  	//If catalog name is provided then get catalog ID using name for further process
catalog item name
catalog item ID

2018-06-02 05:49 UTC, raghavav commented on vrealize/resource.go
>  			return fmt.Errorf("No catalog found with name %v", d.Get("catalog_name").(string))
catalog item

2018-06-04 17:36 UTC, raghavav commented
@virajindasrao 
Can you please take care of the remaining comments on this one so we can get the tests merged in?
Thanks
Vijay

2018-06-05 11:40 UTC, virajindasrao commented on vrealize/resource_test.go
> +	strJson := `{"type":"com.vmware.vcac.catalog.domain.request.CatalogItemProvisioningRequest","catalogItemId":"e5dd4fba-45ed-4943-b1fc-7f96239286be","requestedFor":"jason@corp.local","businessGroupId"
I am thinking of removing JSON data into a separate file to make it more readable.
I will create separate PR for it.

2018-06-05 15:44 UTC, raghavav requested changes

2018-06-05 15:44 UTC, raghavav commented on vrealize/catalog_test.go
> +	// Fetch catalog by false name
catalog item

2018-06-05 15:44 UTC, raghavav commented on vrealize/catalog_test.go
> +	// This should through an error and return an empty catalogItemID value
'throw' not 'through'.
In golang, you actually 'return' an error right?

2018-06-05 15:44 UTC, raghavav commented on vrealize/resource.go
> +	// If catalog_name and catalog_id both not provided then throw an error
'return' an error.

2018-06-05 15:44 UTC, raghavav commented on vrealize/resource.go
> +	//Through an exception if there is any error while getting catalog item template
'Return'

2018-06-06 06:32 UTC, raghavav approved these changes

2018-06-06 06:33 UTC, merged