Issue fix : Terraform destroy runs async (completes immediately)
vmware-archive/legacy-terraform-provider-vra7 pull request #56
Opened 2018-06-14 07:33 UTC by virajindasrao

Issue [#53](https://github.com/vmware/terraform-provider-vra7/issues/53) fix : Terraform destroy runs async (completes immediately)

Signed-off-by: Viraj Indasrao <virajindasrao@gmail.com>

2018-06-19 00:36 UTC, raghavav requested changes

2018-06-19 00:36 UTC, raghavav commented on vrealize/resource.go
> +		time.Sleep(3e+10)
Better to move the sleep to the beginning of the loop.
Sleeping at the end means that you sleep even if deleteFlag becomes true.

2018-06-19 00:36 UTC, raghavav commented on vrealize/resource.go
> +		if len(deploymentStateData.Content) == 0 {
This approach is fine, but I think the right way to do this is to look at the status of the destroy request.
I am fine to make that as a separate change. Looking at the request status is the more correct, API-driven way to know that the destroy is successful.

2018-06-19 00:36 UTC, raghavav commented on vrealize/resource.go
> +	for deleteFlag == false {
We need a timeout to make sure we don't hang forever.

2018-06-20 06:46 UTC, virajindasrao commented on vrealize/resource.go
> +		if len(deploymentStateData.Content) == 0 {
Destroy API returns 201 status only and not the resource action request. Hence,  this check is needed to verify the resource is deleted or not.

2018-06-20 06:49 UTC, virajindasrao commented on vrealize/resource.go
> +	for deleteFlag == false {
Done.

2018-06-20 06:50 UTC, virajindasrao commented on vrealize/resource.go
> +		time.Sleep(3e+10)
Done.

2018-06-20 19:35 UTC, raghavav commented
@virajindasrao I merged master into this branch. I am reviewing this shortly. Do test this change and we can get this merged in.

2018-06-20 20:08 UTC, raghavav requested changes

2018-06-20 20:08 UTC, raghavav commented on vrealize/resource.go
> +		time.Sleep(3e+10)
Why use a floating point number like this? We want to work with a simple integer Duration here.

A better way to code this is
sleepFor := 30
for i := 0; i < waitTimeout/sleepFor; i++ {
    time.Sleep(time.Duration(sleepFor)*time.Second)
    ...

That way the sleep and the number of iterations will always be aligned, instead of having two copies of the number 30 which may change in the future.

2018-06-25 18:00 UTC, raghavav approved these changes
We need a test case for the timeout behavior.
Please create a separate PR for the test case.

2018-06-25 18:00 UTC, merged