README.md changes
vmware-archive/legacy-terraform-provider-vra7 pull request #62
Opened 2018-06-27 12:46 UTC by virajindasrao

Issue #61 fixes
Signed-off-by: Viraj Indasrao <virajindasrao@gmail.com>

2018-07-02 23:03 UTC, raghavav requested changes

2018-07-02 23:03 UTC, raghavav commented on README.md
> +* **wait_timeout** - *wait_timeout is optional field with default value of 15 mins. wait_timeout defines the time to wait until resource comes up or destroys resource successfully*
Please follow the language style that is used in the rest of the document:

"This is an optional field with a default value of 15. It defines the time to wait (in minutes) for a resource operation to complete successfully."

2018-07-03 05:43 UTC, virajindasrao commented on README.md
> +* **wait_timeout** - *wait_timeout is optional field with default value of 15 mins. wait_timeout defines the time to wait until resource comes up or destroys resource successfully*
Done.

2018-07-03 05:55 UTC, raghavav approved these changes

2018-07-03 05:55 UTC, merged