Adding a logging framework for more detailed logging of vRA Terraform plugging.
vmware-archive/legacy-terraform-provider-vra7 pull request #85
Opened 2018-09-24 19:52 UTC by Prativa20

2018-09-24 23:01 UTC, raghavav requested changes
Some comments. Mainly, need to resolve the failing tests in CI, and test it on Windows.

2018-09-24 23:01 UTC, raghavav commented on utils/contants.go
> +
Too many empty lines here. Delete please.

2018-09-24 23:01 UTC, raghavav commented on utils/logger.go
> +	logFile, err := os.OpenFile("./"+terraformVraProviderFileName, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
I'd be more comfortable if someone could test this on a Windows system. For example, the forward slash here worries me.

2018-09-25 03:16 UTC, raghavav approved these changes

2018-09-25 19:17 UTC, Prativa20 commented
Tested on windows as well, works fine!

2018-09-25 19:56 UTC, merged