Fixing the config validation bug # 91
vmware-archive/legacy-terraform-provider-vra7 pull request #92
Opened 2018-10-09 07:42 UTC by Prativa20

Adding logic to check all possible keys in the resource_configuration in config file
and validate if it is a valid component name in the blueprint

Signed-off-by: Prativa Bawri <bawrip@vmware.com>

2018-10-09 07:52 UTC, raghavav requested changes

2018-10-09 07:52 UTC, raghavav commented on vrealize/resource.go
> +		for strings.LastIndex(key, ".") != -1 {
Directly assign lastIndex while doing this check. No need to evaluate twice.

2018-10-09 07:52 UTC, raghavav commented on vrealize/resource.go
> +			key = k[0:lastIndex]
Should be
key = key[0:lastIndex] right?

2018-10-10 20:45 UTC, raghavav requested changes
This is exactly the direction we want to go in for these tests. I have some asks, but for the most part things are good.

2018-10-10 20:45 UTC, raghavav commented on resources/MockRequestTemplate
> +   "requestedFor":"mock@mock.com",
Turns out 'mock.com' is a real business :)

2018-10-10 20:45 UTC, raghavav commented on vrealize/resource_test.go
> +	filePath := ".." + utils.GetPathSeparator() + "resources" + utils.GetPathSeparator() + "MockRequestTemplate"
There is an assumption here about the current directory? Do make sure you test this by running the test from other directories by passing the right directory to 'go test'.

2018-10-10 20:45 UTC, raghavav commented on vrealize/resource_test.go
>  	mockConfigResourceMap["mock.machine3.vSphere.mock.cpu"] = 2
Add a comment in the code to indicate why this is a failure case and what should happen.

2018-10-10 20:59 UTC, raghavav commented on vrealize/resource.go
> +		for strings.LastIndex(key, ".") != -1 {
Did you try to fix this one? Were you able to get it working?

2018-10-10 21:41 UTC, raghavav approved these changes

2018-10-10 21:44 UTC, merged

2018-10-10 21:45 UTC, Prativa20 commented on vrealize/resource.go
> +		for strings.LastIndex(key, ".") != -1 {
Tried the following, but the execution is stuck here and no error is being thrown

for lastIndex := strings.LastIndex(key, "."); lastIndex != -1; {
			key = key[0:lastIndex]
			if _, ok := componentSet[key]; ok {
				log.Info("The component name %s in the terraform config file is valid ", key)
				isValid = true
				break
			}
		}