Adding businessgroup_name in the config file
vmware-archive/legacy-terraform-provider-vra7 pull request #94
Opened 2018-10-11 09:32 UTC by Prativa20

Adding businessgroup_name in the config file to allow requesting catalog item
with business group name as well as id

Signed-off-by: Prativa Bawri <bawrip@vmware.com>

2018-10-11 14:12 UTC, raghavav requested changes

2018-10-11 14:12 UTC, raghavav commented on vrealize/resource.go
> +	if len(business_group_name) > 0 && len(business_group_id) > 0 && businessGroupIdFromName != business_group_id {
To be picky about whitespace checks, consider using:

leng(strings.TrimSpace(...)) > 0 in all these checks

2018-10-11 14:12 UTC, raghavav commented on vrealize/resource.go
> +	path := "identity/api/tenants/" + vRAClient.Tenant + "/subtenants"
Have you checked if vRA already has an API to retrieve business group by name? It very well might. This should be commonly used functionality in the product.

2018-10-11 19:32 UTC, Prativa20 commented on vrealize/resource.go
> +	path := "identity/api/tenants/" + vRAClient.Tenant + "/subtenants"
Checked the vRA API doc, there is no such API for filtering based on name.

2018-10-11 19:34 UTC, Prativa20 commented on vrealize/resource.go
> +	if len(business_group_name) > 0 && len(business_group_id) > 0 && businessGroupIdFromName != business_group_id {
This might not work when the string has more than one word, say, the BG name is "Quality Engineering". Can do this check for id though.

2018-10-12 00:48 UTC, raghavav commented on vrealize/resource.go
> +	if len(business_group_name) > 0 && len(business_group_id) > 0 && businessGroupIdFromName != business_group_id {
No, TrimSpace only trims from the ends, not in the middle of strings.

2018-10-15 00:59 UTC, Prativa20 commented on vrealize/resource.go
> +	if len(business_group_name) > 0 && len(business_group_id) > 0 && businessGroupIdFromName != business_group_id {
Right!
Using TrimSpace while reading BG id and name.

2018-10-15 01:00 UTC, Prativa20 commented on vrealize/resource.go
> +	path := "identity/api/tenants/" + vRAClient.Tenant + "/subtenants"
Using the filter-based OData query to get the BG object based on name

2018-10-15 03:04 UTC, raghavav requested changes
Changes look pretty close to done. Just a couple of items.

2018-10-15 03:04 UTC, raghavav commented on vrealize/resource.go
> +	business_group_name := strings.TrimSpace(d.Get("businessgroup_name").(string))
Not sure about golang, but what happens if TrimSpace gets a nil value? This could happen if the user does not provide a businessgroup_name value.

2018-10-15 03:04 UTC, raghavav commented on vrealize/resource.go
> +		return "", err
better to return nil (and the error of course) in the event of an error, I think.

2018-10-15 05:25 UTC, Prativa20 commented on vrealize/resource.go
> +	business_group_name := strings.TrimSpace(d.Get("businessgroup_name").(string))
The Get in d.Get("key") takes care of that. If the key is not provided in the config but exists in the schema, it returns the default value for that type. Here, it will return an empty string. So, this will be taken care.

2018-10-15 05:27 UTC, Prativa20 commented on vrealize/resource.go
> +		return "", err
Here the return type is string(the BG id), which does not accept nil as a value.

2018-10-15 05:40 UTC, raghavav commented on vrealize/resource.go
> +		return "", err
plead my ignorance here. thanks.

2018-10-15 05:41 UTC, raghavav approved these changes

2018-10-15 18:45 UTC, merged